api_platform:
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    title: 'API REST Liv&Co'
    description: 'API RESTful permettant la gestion complète des annonces, réservations, utilisateurs et services de la plateforme de coliving Liv&Co visible ici :https://liv-and-co.vercel.app '
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header


                