api_platform:
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    title: 'API REST Liv&Co'
    description: 'Api description nouveau test'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header


                